name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # 在 linux 上运行构建 (必要的话可以改为 windows)
    runs-on: ubuntu-latest

    # 初始化构建工具
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: gradle
      # 修改权限并进行构建
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      # 查找构建好的文件
      # 这里为寻找.apk 和.aar 后缀文件的路径
      - name: find apk
        run:  find ./ -regex ".*\.apk\|.*\.aar"

      # 将构建好的含.apk 的文件上传
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name:  ok
          path: app/release/*.apk
    #这里的 path 路径是来自于 find apk 那一步的结果